allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause

ignored:
  go:
    # ignore all go packages from import paths starting with github.com/internal-package
    # see the `File.fnmatch?` documentation for details on how patterns are matched.
    # comparisons use the FNM_CASEFOLD and FNM_PATHNAME flags
    - golang.org/x/**/*

apps:
  - source_path: 'pkg'
    sources:
      go:
        mod: vendor
